from playwright.sync_api import sync_playwright
import time

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page_one = browser.new_page()
    page_two = browser.new_page()
    page_one.goto('https://staging-payment-pro.blusalt.net/')
    page_two.goto('https://staging-payment-pro.blusalt.net/')
    page_one.fill('#email', "endurance+1070@blusalt.net")
    page_two.fill('#email', "endurance+1070@blusalt.net")
    page_two.fill('#password', "Ekundayo1989@")
    page_one.fill('#password', "Ekundayo1989@")
    page_one.click("button[type='submit']")     
    page_two.click("button[type='submit']")
    page_one.wait_for_selector("//a[@href='/payment-gateway/transactions']//span")
    page_two.wait_for_selector("//a[@href='/payment-gateway/transactions']//span")
    page_one.click("//a[@href='/payment-gateway/transactions']//span")
    page_two.click("//a[@href='/payment-gateway/transactions']//span")
    page_one.click('a[href="/payment-gateway/transactions/disputes"]')
    page_two.click('a[href="/payment-gateway/transactions/disputes"]')
    page_one.click("div[id='transactions-nav-tab'] span")
    page_two.click("div[id='transactions-nav-tab'] span")
    page_one.fill('#title', "playwright")
    page_two.fill('#title', "playwright")
    page_one.fill('#description', 'testing')
    page_two.fill('#description', 'testing')
    page_one.click('#type')
    page_two.click('#type')
    page_one.get_by_role("option", name="Fraud").click()
    page_two.get_by_role("option", name="Fraud").click()
    page_one.fill('#payment_reference','TCH-51_GlMtlv')
    page_two.fill('#payment_reference','TCH-51_GlMtlv')
    page_one.locator('#category').click()
    page_two.locator('#category').click()
    page_one.get_by_role("option", name="Payroll").click()
    page_two.get_by_role("option", name="Payroll").click()
    page_two.set_input_files('input[type="file"]', "use.png")
    page_one.set_input_files('input[type="file"]', "use.png")
    page_one.click("button[type='submit']")
    page_two.click("button[type='submit']")
    time.sleep(4)
    page_one.screenshot(path="use.png")
    page_two.screenshot(path="use.png")
    time.sleep(4)
    assert(page_one.locator('section[aria-label="Notifications alt+T"]')).is_visible()
    assert(page_two.locator('section[aria-label="Notifications alt+T"]')).is_visible()
    print(page_one.title())
    print(page_two.title())
    browser.close()

